
package com.castillo.jaxws.clientes;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Clientes", targetNamespace = "http://clientes.jaxws.castillo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Clientes {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.castillo.jaxws.clientes.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarCliente", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.EliminarCliente")
    @ResponseWrapper(localName = "eliminarClienteResponse", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.EliminarClienteResponse")
    public Cliente eliminarCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.castillo.jaxws.clientes.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerClientes", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.ObtenerClientes")
    @ResponseWrapper(localName = "obtenerClientesResponse", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.ObtenerClientesResponse")
    public List<Cliente> obtenerClientes();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.castillo.jaxws.clientes.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerId", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.ObtenerId")
    @ResponseWrapper(localName = "obtenerIdResponse", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.ObtenerIdResponse")
    public Cliente obtenerId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.castillo.jaxws.clientes.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarCliente", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.AgregarCliente")
    @ResponseWrapper(localName = "agregarClienteResponse", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.AgregarClienteResponse")
    public Cliente agregarCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.castillo.jaxws.clientes.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarCliente", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.ActualizarCliente")
    @ResponseWrapper(localName = "actualizarClienteResponse", targetNamespace = "http://clientes.jaxws.castillo.com/", className = "com.castillo.jaxws.clientes.ActualizarClienteResponse")
    public Cliente actualizarCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

}
