
package com.castillo.jaxws.clientes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientesImplService", targetNamespace = "http://clientes.jaxws.castillo.com/", wsdlLocation = "http://localhost:8080/HelloJAXWS/Clientes?wsdl")
public class ClientesImplService
    extends Service
{

    private final static URL CLIENTESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTESIMPLSERVICE_EXCEPTION;
    private final static QName CLIENTESIMPLSERVICE_QNAME = new QName("http://clientes.jaxws.castillo.com/", "ClientesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/HelloJAXWS/Clientes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTESIMPLSERVICE_WSDL_LOCATION = url;
        CLIENTESIMPLSERVICE_EXCEPTION = e;
    }

    public ClientesImplService() {
        super(__getWsdlLocation(), CLIENTESIMPLSERVICE_QNAME);
    }

    public ClientesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTESIMPLSERVICE_QNAME, features);
    }

    public ClientesImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTESIMPLSERVICE_QNAME);
    }

    public ClientesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTESIMPLSERVICE_QNAME, features);
    }

    public ClientesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Clientes
     */
    @WebEndpoint(name = "ClientesImplPort")
    public Clientes getClientesImplPort() {
        return super.getPort(new QName("http://clientes.jaxws.castillo.com/", "ClientesImplPort"), Clientes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Clientes
     */
    @WebEndpoint(name = "ClientesImplPort")
    public Clientes getClientesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://clientes.jaxws.castillo.com/", "ClientesImplPort"), Clientes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTESIMPLSERVICE_EXCEPTION!= null) {
            throw CLIENTESIMPLSERVICE_EXCEPTION;
        }
        return CLIENTESIMPLSERVICE_WSDL_LOCATION;
    }

}
